#!/usr/bin/env bash
# CTV OS — create the Supabase project and push the schema, without a browser.
#
#   SUPABASE_ACCESS_TOKEN=sbp_... ./scripts/provision_supabase.sh
#
# Everything here is non-interactive. The one thing that cannot be is minting
# the access token: that needs a signed-in browser session on your account, at
#   https://supabase.com/dashboard/account/tokens
# Paste it in as SUPABASE_ACCESS_TOKEN and the rest of this runs unattended.
#
# Safe to re-run. If a project called $PROJECT_NAME already exists in the org it
# links to that one instead of creating a second.
#
# Optional overrides:
#   PROJECT_NAME   default "ctv-os"
#   REGION         default "eu-west-2" (London — the station is in Bath)
#   ORG_ID         default: the only org on the account, else you must set it
#   DB_PASSWORD    default: generated and written to .env.local

set -euo pipefail

PROJECT_NAME="${PROJECT_NAME:-ctv-os}"
REGION="${REGION:-eu-west-2}"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.local"

if [[ -z "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
  cat >&2 <<'MSG'
SUPABASE_ACCESS_TOKEN is not set.

Generate one at https://supabase.com/dashboard/account/tokens (it starts
"sbp_"), then:

    SUPABASE_ACCESS_TOKEN=sbp_xxx ./scripts/provision_supabase.sh

This is the only step that needs a browser. Everything after it is headless.
MSG
  exit 1
fi

step() { printf '\n\033[1m%s\033[0m\n' "$*"; }

step "1/6  Checking the token"
supabase projects list --output json >/dev/null

# --- organisation ---------------------------------------------------------
step "2/6  Finding the organisation"
if [[ -z "${ORG_ID:-}" ]]; then
  ORG_COUNT=$(supabase orgs list --output json | python3 -c 'import json,sys; print(len(json.load(sys.stdin)))')
  if [[ "$ORG_COUNT" != "1" ]]; then
    echo "Found $ORG_COUNT organisations. Pick one and re-run with ORG_ID=<id>:" >&2
    supabase orgs list >&2
    exit 1
  fi
  ORG_ID=$(supabase orgs list --output json | python3 -c 'import json,sys; print(json.load(sys.stdin)[0]["id"])')
fi
echo "  org: $ORG_ID"

# --- password -------------------------------------------------------------
# Generated rather than prompted, and written to .env.local, which is gitignored.
# The database password is not recoverable from the dashboard afterwards.
if [[ -z "${DB_PASSWORD:-}" ]]; then
  if [[ -f "$ENV_FILE" ]] && grep -q '^SUPABASE_DB_PASSWORD=' "$ENV_FILE"; then
    DB_PASSWORD=$(grep '^SUPABASE_DB_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)
    echo "  reusing the password already in .env.local"
  else
    DB_PASSWORD=$(python3 -c 'import secrets,string; a=string.ascii_letters+string.digits; print("".join(secrets.choice(a) for _ in range(32)))')
  fi
fi

# --- project --------------------------------------------------------------
step "3/6  Project \"$PROJECT_NAME\""
REF=$(supabase projects list --output json \
  | python3 -c "import json,sys; ps=[p for p in json.load(sys.stdin) if p['name']=='$PROJECT_NAME']; print(ps[0]['id'] if ps else '')")

if [[ -n "$REF" ]]; then
  echo "  already exists: $REF"
else
  echo "  creating in $REGION (this takes a minute or two)"
  supabase projects create "$PROJECT_NAME" \
    --org-id "$ORG_ID" --db-password "$DB_PASSWORD" --region "$REGION"
  REF=$(supabase projects list --output json \
    | python3 -c "import json,sys; print([p for p in json.load(sys.stdin) if p['name']=='$PROJECT_NAME'][0]['id'])")
  echo "  created: $REF"
fi

# --- credentials ----------------------------------------------------------
step "4/6  Writing .env.local"
API_URL="https://${REF}.supabase.co"
# Pooler host, because a laptop on eduroam behind IPv4 cannot reach the direct
# db.<ref>.supabase.co host, which is IPv6-only on new projects.
DB_URL="postgresql://postgres.${REF}:${DB_PASSWORD}@aws-0-${REGION}.pooler.supabase.com:5432/postgres"
ANON_KEY=$(supabase projects api-keys --project-ref "$REF" --output json 2>/dev/null \
  | python3 -c 'import json,sys
try:
    ks = json.load(sys.stdin)
    print(next((k["api_key"] for k in ks if k["name"] == "anon"), ""))
except Exception:
    print("")')

umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/provision_supabase.sh — gitignored, do not commit.
SUPABASE_PROJECT_REF=$REF
SUPABASE_URL=$API_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_DB_PASSWORD=$DB_PASSWORD
SUPABASE_DB_URL=$DB_URL
EOF
echo "  $ENV_FILE"

# --- wait for the database to accept connections --------------------------
step "5/6  Waiting for the database"
for i in $(seq 1 40); do
  if supabase link --project-ref "$REF" --password "$DB_PASSWORD" >/dev/null 2>&1; then
    echo "  linked"
    break
  fi
  [[ $i -eq 40 ]] && { echo "  still not ready after ~7 minutes — re-run this script" >&2; exit 1; }
  sleep 10
done

# --- schema ---------------------------------------------------------------
step "6/6  Pushing the schema"
python3 "$(dirname "$0")/sync_migration.py" --check
supabase db push --password "$DB_PASSWORD" --include-all

cat <<EOF

Done. Project $REF is up and the schema is on it.

  Verify it for real:   npm run verify:remote
  Dashboard:            https://supabase.com/dashboard/project/$REF

Credentials are in .env.local (gitignored). The database password cannot be
read back from the dashboard, so keep that file.
EOF
